### ISSUE TITLE
Website hidden beneath pop-up on iPhone 6+ iOS 8.3 safari

### ISSUE THREAD

**Issue by pmasher** [DuxterInc/trendy-community#224] opened 2015-10-20 03:15 UTC
All I see when I load any website page is the following image. I cannot click x or get past it in any way.

http://i.imgur.com/zF9IdVs.jpg

**Comment by adamlieb** [comment] 2015-10-20 03:24
iPhone 6+, Safari, iOS 8.3

@pmasher have you logged in/out? Cleared your cache? Those would be the next two steps.

**Comment by pmasher** [comment] 2015-11-03 15:55
Yep, completely cleared browsing history and it's still there. I get the about page, and as soon as I continue this is all that is there.

**Comment by adamlieb** [comment] 2015-11-06 20:11
also have you tried using "private mode" in safari, to see if the same thing happens?

**Comment by pmasher** [comment] 2015-11-06 20:13
On private I just get:

[image1.PNG]

-Philip

Sent from my iPhone

On Nov 6, 2015, at 3:11 PM, Adam Lieb <notifications@github.com<mailto:notifications@github.com>> wrote:


also have you tried using "private mode" in safari, to see if the same thing happens?

-

**Comment by adamlieb** [comment] 2015-11-06 20:14
No Image is attached, just the title of the image

**Comment by TrendyEnt-I-PASS-BUTTER** [comment] 2016-01-26 16:30
This has also been reported by a player using Samsung Note 4 - Android 5.11

**Comment by adamlieb** [comment] 2016-01-26 16:32
@TrendyEnt-I-PASS-BUTTER can you please ask this user to post screenshots and a repro process and we can investigate right away?

**Comment by pmasher** [comment] 2016-01-26 19:44
This is the same issue that I have on my phone, that prevents me from ever using the website on my phone. There are a few others in the office that also have this issue (same iPhone and update).

-Philip

**Comment by adamlieb** [comment] 2016-01-27 00:45
The issue on our end remains the same. We have no way to reproduce this. We've tried with emulators. I literally have the exact same phone as you do and both of our user accounts are admins. There really aren't any differences between the two of us in setup, except for behavior, which is what we need in order to fix this. If anyone has any repro steps (on any device) that would be extremely helpful. 

It would be especially helpful for whoever reported it on an android device to report their steps, until this point the only report we had was Phil's on an iOS device.

**Comment by TrendyEnt-I-PASS-BUTTER** [comment] 2016-01-27 18:44
From the user..."I logged into the mobile site, and all I saw was the notifications." I'm also getting reports that it is happening on iOS 8.3 using sfari and then chrome.

**Comment by TrendyEnt-I-PASS-BUTTER** [comment] 2016-01-27 18:45
There's been some mention that this might be happening if a user hasn't logged in for a while and cleared their notifications. So a repro step might be to give yourselves a backlog of unseen notifications and then try to log into the site from mobile.

**Comment by rsyvarth** [comment] 2016-01-29 16:45
I believe this is fixed now. We couldn't reproduce on a physical device so would appreciate it if you could confirm and close this issue if it is resolved.

**Comment by pmasher** [comment] 2016-01-29 17:01
This is resolved now! This is the first time this has worked on my phone in months!

-Philip

**Closed** 2016-01-29 17:05 UTC
