### ISSUE TITLE
HTML Anchor for SignUp

### ISSUE THREAD

**Issue by CatFerry** [DuxterInc/trendy-community#223] opened 2015-10-07 20:29 UTC
On https://dungeondefenders.com/2/about when you click SIGN UP FOR OPEN ALHPA, it brings you to the bottom. Create an HTML anchor to directly send people to this location. Maybe something like https://dungeondefenders.com/2/about/#Signup

**Comment by adamlieb** [comment] 2015-10-16 20:51
Closing this out as it is not a bug. This is about 8 hours worth of work that requires restructuring the entire page. Trying to keep this repo clean for just bugs so we can make sure they are resolved.

**Closed by adamlieb** 2015-10-16 20:51 UTC
Labels: feature request
